### ISSUE TITLE
ServerThread/ERROR

### ISSUE THREAD

**Issue by Karounac58** [SAGESSE-CN/Armourers-Workshop-Plugin#14]
> [13:03:44] [Server thread/ERROR]: Error occurred while enabling armourers_workshop v2.1.2 (Is it up to date?)
java.lang.RuntimeException: java.lang.NullPointerException: Cannot read the array length because "\<local1\>" is null
	at moe.plushie.armourers_workshop.core.data.DataManager.connect(DataManager.java:47) ~[armourersworkshop-plugin-2.1.2.jar:?]
	at moe.plushie.armourers_workshop.ArmourersWorkshopPlugin.onEnable(ArmourersWorkshopPlugin.java:50) ~[armourersworkshop-plugin-2.1.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot read the array length because "\<local1\>" is null
	at moe.plushie.armourers_workshop.core.data.source.SkinFileDataSource$Local.loadNodes(SkinFileDataSource.java:239) ~[armourersworkshop-plugin-2.1.2.jar:?]
	at moe.plushie.armourers_workshop.core.data.source.SkinFileDataSource$Local.connect(SkinFileDataSource.java:186) ~[armourersworkshop-plugin-2.1.2.jar:?]
	at moe.plushie.armourers_workshop.core.data.DataManager.connect(DataManager.java:39) ~[armourersworkshop-plugin-2.1.2.jar:?]
	... 13 more

**Comment by Karounac58** [comment]
because ""，双引号里的是<local1>

**Comment by SAGESSE-CN** [comment]
remove the config and then retry

**Comment by Karounac58** [comment]
> remove the config and then retry

我删了plugins/armourers_workshop/config，重载了还是一样

**Comment by SAGESSE-CN** [comment]
配置上面写的啥，另外最好重启 而不是重载

**Comment by Karounac58** [comment]
> 配置上面写的啥，另外最好重启 而不是重载

配置没动，是默认的。我第一次用就是重启服务器，然后报这个错误

**Comment by SAGESSE-CN** [comment]
奇怪，现在的配置应该是空字符串吧

**Comment by Karounac58** [comment]
`#General settings.
general:
  #Max number of undos a player has for block painting.
  #Range: 0 ~ 1000
  maxUndos: 100
  #Max number of processing blocks in per tick.
  #Range: 1 ~ 1000
  blockTaskRate: 10
  #When enabled players will not be able to remove dyes from skins in the dye table.
  lockDyesOnSkins: false
  #If true the dye table will be instanced for each player. Items will be dropped when the table is closed.
  instancedDyeTable: false
  #If enabled the server will check the client protocol version in the login.
  #Highly recommended unless the server does not support handshake.
  enableProtocolCheck: true
  #The maximum number of skins the server is allow to send every minute.
  #Less that 1 equals unlimited. (not recommended may cause bandwidth and cpu spikes on the server)
  #Range: 0 ~ 8000
  serverModelSendRate: 4000
  #If enabled the server will compress skins before sending them to clients.
  #Highly recommended unless the server has a very slow CPU.
  serverCompressesSkins: true
  #Using embedded skin renderer to replace the original item renderer.
  #0 = use client config
  #1 = always disable
  #2 = always enable
  #Range: 0 ~ 2
  enableEmbeddedSkinRenderer: 0
  #Using skin renderer to replace the original first person hands renderer.
  #0 = use client config
  #1 = always disable
  #2 = always enable
  #Range: 0 ~ 2
  enableFirstPersonSkinRenderer: 0
#Setting for the players wardrobe.
wardrobe:
  #Allow the player to open the wardrobe GUI.
  allowOpening: true
  #Enable the wardrobe skins tab.
  enableSkinTab: true
  #Enable the wardrobe outfits tab.
  enableOutfitTab: true
  #Enable the wardrobe display settings tab.
  enableDisplayTab: true
  #Enable the wardrobe colour settings tab.
  enableColourTab: true
  #Enable the wardrobe dyes tab.
  enableDyeTab: true
  #Number of slot columns the mob starts with for skins.
  #Range: 1 ~ 10
  mobStartingSlots: 3
  #Number of slot columns the player starts with for skins.
  #Range: 1 ~ 10
  playerStartingSlots: 3
  #Should skins be dropped on player death.
  #0 = use keep inventory rule
  #1 = never drop
  #2 = always drop
  #Range: 0 ~ 2
  playerDropSkinsOnDeath: 0
#Setting for the library blocks.
library:
  #Allows clients to save skins from a server to their local computer using the library.
  allowDownloadingSkins: false
  #Allows clients to load skins from their local computer onto the server using the library.
  allowUploadingSkins: true
  #Allow the mod to extract the official skins that come with the mod into the library folder.
  extractOfficialSkins: false
  #Shows model previews in the library.
  #Causes a lot of extra load on servers.
  #Best to turn off on high population servers
  allowPreviewSkins: true
  #Allows clients to manage skins of the server computer library.
  #Required permission level 5 or higher.
  allowManageSkins: false
  #We priority use https for the access token APIs.
  skinServerURLs: []
#Setting for the Database.
database:
  #Save/Load skin data for the database.
  #example1: 'jdbc:mysql://<localhost>[:3306]/<database>[?user=<username>][&password=<password>]'
  #example2: 'jdbc:sqlite://</path/name.db>'
  skin: ''
  #Save/Load wardrobe data for the database.
  #example1: 'jdbc:mysql://<localhost>[:3306]/<database>[?user=<username>][&password=<password>]'
  #example2: 'jdbc:sqlite://</path/name.db>'
  wardrobe: ''
#Enable/disable holiday events.
holiday-events:
  #Setting to true will disable all holiday events. What's wrong with you!
  disableAllHolidayEvents: false
#Change (memory use/IO access) ratio by category setting in this category.
cache:
  #How long in seconds the server will keep skins in it's cache.
  #Default 600 seconds is 10 minutes.
  #Setting to 0 turns off this option.
  #Range: 0 ~ 36000
  expireTime: 600
  #Max size the skin cache can reach before skins are removed.
  #Setting to 0 turns off this option.
  #Range: 0 ~ 10000
  maxSize: 2000
#Custom list of items that can be skinned.
overrides:
  #Format ["override type:mod id:item name"]
  #Valid override types are: sword, shield, bow, pickaxe, axe, shovel, hoe and item
  #example ["sword:minecraft:iron_sword","sword:minecraft:gold_sword"]
  itemOverrides: []
  #Tries to automatically assign the correct type of skin type without config and tag.
  enableMatchingByItemId: true
  #If the matching system wrong, you can add the item id here to this ignore it.
  matchingBlacklistByItemId: []
`

> 奇怪，现在的配置应该是空字符串吧

**Comment by Karounac58** [comment]
> 奇怪，现在的配置应该是空字符串吧

#General settings.
general:
  #Max number of undos a player has for block painting.
  #Range: 0 ~ 1000
  maxUndos: 100
  #Max number of processing blocks in per tick.
  #Range: 1 ~ 1000
  blockTaskRate: 10
  #When enabled players will not be able to remove dyes from skins in the dye table.
  lockDyesOnSkins: false
  #If true the dye table will be instanced for each player. Items will be dropped when the table is closed.
  instancedDyeTable: false
  #If enabled the server will check the client protocol version in the login.
  #Highly recommended unless the server does not support handshake.
  enableProtocolCheck: true
  #The maximum number of skins the server is allow to send every minute.
  #Less that 1 equals unlimited. (not recommended may cause bandwidth and cpu spikes on the server)
  #Range: 0 ~ 8000
  serverModelSendRate: 4000
  #If enabled the server will compress skins before sending them to clients.
  #Highly recommended unless the server has a very slow CPU.
  serverCompressesSkins: true
  #Using embedded skin renderer to replace the original item renderer.
  #0 = use client config
  #1 = always disable
  #2 = always enable
  #Range: 0 ~ 2
  enableEmbeddedSkinRenderer: 0
  #Using skin renderer to replace the original first person hands renderer.
  #0 = use client config
  #1 = always disable
  #2 = always enable
  #Range: 0 ~ 2
  enableFirstPersonSkinRenderer: 0
#Setting for the players wardrobe.
wardrobe:
  #Allow the player to open the wardrobe GUI.
  allowOpening: true
  #Enable the wardrobe skins tab.
  enableSkinTab: true
  #Enable the wardrobe outfits tab.
  enableOutfitTab: true
  #Enable the wardrobe display settings tab.
  enableDisplayTab: true
  #Enable the wardrobe colour settings tab.
  enableColourTab: true
  #Enable the wardrobe dyes tab.
  enableDyeTab: true
  #Number of slot columns the mob starts with for skins.
  #Range: 1 ~ 10
  mobStartingSlots: 3
  #Number of slot columns the player starts with for skins.
  #Range: 1 ~ 10
  playerStartingSlots: 3
  #Should skins be dropped on player death.
  #0 = use keep inventory rule
  #1 = never drop
  #2 = always drop
  #Range: 0 ~ 2
  playerDropSkinsOnDeath: 0
#Setting for the library blocks.
library:
  #Allows clients to save skins from a server to their local computer using the library.
  allowDownloadingSkins: false
  #Allows clients to load skins from their local computer onto the server using the library.
  allowUploadingSkins: true
  #Allow the mod to extract the official skins that come with the mod into the library folder.
  extractOfficialSkins: false
  #Shows model previews in the library.
  #Causes a lot of extra load on servers.
  #Best to turn off on high population servers
  allowPreviewSkins: true
  #Allows clients to manage skins of the server computer library.
  #Required permission level 5 or higher.
  allowManageSkins: false
  #We priority use https for the access token APIs.
  skinServerURLs: []
#Setting for the Database.
database:
  #Save/Load skin data for the database.
  #example1: 'jdbc:mysql://<localhost>[:3306]/<database>[?user=<username>][&password=<password>]'
  #example2: 'jdbc:sqlite://</path/name.db>'
  skin: ''
  #Save/Load wardrobe data for the database.
  #example1: 'jdbc:mysql://<localhost>[:3306]/<database>[?user=<username>][&password=<password>]'
  #example2: 'jdbc:sqlite://</path/name.db>'
  wardrobe: ''
#Enable/disable holiday events.
holiday-events:
  #Setting to true will disable all holiday events. What's wrong with you!
  disableAllHolidayEvents: false
#Change (memory use/IO access) ratio by category setting in this category.
cache:
  #How long in seconds the server will keep skins in it's cache.
  #Default 600 seconds is 10 minutes.
  #Setting to 0 turns off this option.
  #Range: 0 ~ 36000
  expireTime: 600
  #Max size the skin cache can reach before skins are removed.
  #Setting to 0 turns off this option.
  #Range: 0 ~ 10000
  maxSize: 2000
#Custom list of items that can be skinned.
overrides:
  #Format ["override type:mod id:item name"]
  #Valid override types are: sword, shield, bow, pickaxe, axe, shovel, hoe and item
  #example ["sword:minecraft:iron_sword","sword:minecraft:gold_sword"]
  itemOverrides: []
  #Tries to automatically assign the correct type of skin type without config and tag.
  enableMatchingByItemId: true
  #If the matching system wrong, you can add the item id here to this ignore it.
  matchingBlacklistByItemId: []

**Comment by Karounac58** [comment]
> 奇怪，现在的配置应该是空字符串吧

要不加下qq啥的

**Comment by SAGESSE-CN** [comment]
哦， 找到问题了。464323854 你可以加这个群

**Comment by SAGESSE-CN** [comment]
fixed in 2.1.3

**Comment by Karounac58** [comment]
> fixed in 2.1.3

找不到这个群

**Comment by SAGESSE-CN** [comment]
再搜一次
